[build]
  command = "npm install && npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_ANALYTICS_ID = "your-id"

[context.production.environment]
  NODE_ENV = "production"