[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_ANALYTICS_ID = "your-id"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_TYPE_CHECK = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"