[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production.environment]
  NEXT_PUBLIC_ANALYTICS_ID = "your-id"